import type { Config } from "tailwindcss";

// Design tokens sourced verbatim from the Stitch export:
// stitch_unified_enterprise_cyber_defense/sentinel_oversight/DESIGN.md
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#031427",
        "surface-dim": "#031427",
        "surface-bright": "#2a3a4f",
        "surface-container-lowest": "#000f21",
        "surface-container-low": "#0b1c30",
        "surface-container": "#102034",
        "surface-container-high": "#1b2b3f",
        "surface-container-highest": "#26364a",
        "on-surface": "#d3e4fe",
        "on-surface-variant": "#c6c6cd",
        "inverse-surface": "#d3e4fe",
        "inverse-on-surface": "#213145",
        outline: "#909097",
        "outline-variant": "#45464d",
        "surface-tint": "#bec6e0",
        primary: "#bec6e0",
        "on-primary": "#283044",
        "primary-container": "#0f172a",
        "on-primary-container": "#798098",
        "inverse-primary": "#565e74",
        secondary: "#7bd0ff",
        "on-secondary": "#00354a",
        "secondary-container": "#00a6e0",
        "on-secondary-container": "#00374d",
        tertiary: "#4edea3",
        "on-tertiary": "#003824",
        "tertiary-container": "#001c10",
        "on-tertiary-container": "#009365",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#dae2fd",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-fixed": "#131b2e",
        "on-primary-fixed-variant": "#3f465c",
        "secondary-fixed": "#c4e7ff",
        "secondary-fixed-dim": "#7bd0ff",
        "on-secondary-fixed": "#001e2c",
        "on-secondary-fixed-variant": "#004c69",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        background: "#031427",
        "on-background": "#d3e4fe",
        "surface-variant": "#26364a",
      },
      fontFamily: {
        display: ["Hanken Grotesk", "sans-serif"],
        headline: ["Hanken Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Geist", "monospace"],
        mono: ["Geist", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.05em" }],
        "mono-data": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        gutter: "24px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      boxShadow: {
        "glow-cyan": "0 0 10px rgba(123, 208, 255, 0.5)",
        "glow-critical": "0 0 15px rgba(255, 180, 171, 0.6)",
      },
      keyframes: {
        "pulse-critical": {
          "0%, 100%": { boxShadow: "0 0 5px rgba(255, 180, 171, 0.3)" },
          "50%": { boxShadow: "0 0 18px rgba(255, 180, 171, 0.7)" },
        },
      },
      animation: {
        "pulse-critical": "pulse-critical 2s infinite ease-in-out",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};

export default config;
